site_name: CDF2FHIR
site_description: Data Harmonization Framework for Cohort Studies
strict: true
site_url: https://github.com/MyDigiTwinNL/CDF2Medmij-Mapping-tool

theme:
  # https://squidfunk.github.io/mkdocs-material/
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light blue
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: light blue
    accent: indigo
    toggle:
      icon: material/weather-night
      name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
  icon:
    logo: 'material/library-outline'
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: 'favicon.png'

repo_name: MyDigiTwinNL/CDF2Medmij-Mapping-tool
repo_url: https://github.com/MyDigiTwinNL/CDF2Medmij-Mapping-tool
edit_uri: edit/dev/docs/

# https://www.mkdocs.org/user-guide/configuration/#validation
#validation:
#  omitted_files: warn
#  absolute_links: warn
#  unrecognized_links: warn

nav:
- Developer documentation:
  - Introduction: index.md
  - Design overview: arch.md  
- Data harmonization documentation:
  #- Developing pairing rules: prules.md
  - Developing pairing rules: wip.md
  #- Adding support for new FHIR resources: ftemplates.md
  - Adding support for new FHIR resources: wip.md
  

markdown_extensions:
# https://python-markdown.github.io/extensions/
- toc:
    permalink: true
- admonition
# https://facelessuser.github.io/pymdown-extensions
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    pygments_lang_class: true
- pymdownx.extra:
    pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.magiclink

watch:
- docs

plugins:
- search